"""create media table

Revision ID: 147c3d1fc707
Revises: f52bdc6b0961
Create Date: 2026-09-02 23:31:41.608994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "147c3d1fc707"
down_revision: Union[str, Sequence[str], None] = "f52bdc6b0961"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("public_url", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("folder", sa.String(length=100), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size >= 0", name="ck_media_size"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_media_created_at", "media", ["created_at"], unique=False)
    op.create_index("ix_media_folder", "media", ["folder"], unique=False)
    op.create_index(op.f("ix_media_storage_key"), "media", ["storage_key"], unique=True)
    op.create_index(op.f("ix_media_uploaded_by"), "media", ["uploaded_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_uploaded_by"), table_name="media")
    op.drop_index(op.f("ix_media_storage_key"), table_name="media")
    op.drop_index("ix_media_folder", table_name="media")
    op.drop_index("ix_media_created_at", table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
